Repository Kethableez/AnyTravel, pull requests merged in 2022-03, with the labels that each got.

#17 Login, registration works
  .gitignore
  .vscode/settings.json
  api/.eslintrc.json
  api/source/controllers/user.ts
  api/source/functions/activation-data.ts
  api/source/functions/sign-jwt.ts
  api/source/middleware/id-validator.ts
  api/source/middleware/jwt-validator.ts
  api/source/models/interfaces/user.ts
  api/source/models/schemas/user.ts
  api/source/routes/user.ts
  api/source/server.ts
Labels: backend

#18 Login, Register done. Fetching user data after login done
  .vscode/settings.json
  api/source/controllers/user.ts
  api/source/middleware/id-validator.ts
  api/source/routes/user.ts
  app/package-lock.json
  app/package.json
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/core/models/module-name.model.ts
  app/src/app/core/models/response-with-error.model.ts
  app/src/app/core/models/response.model.ts
  app/src/app/core/models/user/login-payload.ts
  app/src/app/core/models/user/login-response.ts
  app/src/app/core/models/user/register-payload.ts
  app/src/app/core/models/user/user.model.ts
  app/src/app/core/services/token.service.ts
  app/src/app/core/services/user/user.service.ts
  app/src/app/core/store/auth/auth-state.module.ts
  app/src/app/core/store/auth/auth.actions.ts
  app/src/app/core/store/auth/auth.effects.ts
  app/src/app/core/store/auth/auth.reducers.ts
  app/src/app/core/store/auth/auth.selectors.ts
  app/src/app/core/store/auth/index.ts
  app/src/app/core/store/user/index.ts
  app/src/app/core/store/user/user-state.module.ts
  app/src/app/core/store/user/user.actions.ts
  app/src/app/core/store/user/user.effects.ts
  app/src/app/core/store/user/user.reducers.ts
  app/src/app/core/store/user/user.selectors.ts
  app/src/app/modules/landing-page/components/login/login.component.html
  app/src/app/modules/landing-page/components/login/login.component.ts
  app/src/app/modules/landing-page/components/register/register.component.html
  app/src/app/modules/landing-page/components/register/register.component.ts
  app/src/app/modules/landing-page/landing-page.component.html
  app/src/app/modules/landing-page/landing-page.component.scss
  app/src/app/modules/landing-page/landing-page.component.ts
  app/src/app/modules/main-page/components/navigation/navigation.component.html
  app/src/app/modules/main-page/components/navigation/navigation.component.scss
  app/src/app/modules/main-page/components/navigation/navigation.component.spec.ts
  app/src/app/modules/main-page/components/navigation/navigation.component.ts
  app/src/app/modules/main-page/main-page-routing.module.ts
  app/src/app/modules/main-page/main-page.component.html
  app/src/app/modules/main-page/main-page.component.scss
  app/src/app/modules/main-page/main-page.component.spec.ts
  app/src/app/modules/main-page/main-page.component.ts
  app/src/app/modules/main-page/main-page.module.ts
Labels: backend, frontend

#23 Profile Tab
  app/angular.json
  app/package-lock.json
  app/package.json
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/core/store/user/index.ts
  app/src/app/core/store/user/user.selectors.ts
  app/src/app/modules/main-page/components/navigation/navigation.component.html
  app/src/app/modules/main-page/components/navigation/navigation.component.ts
  app/src/app/modules/main-page/components/profile/profile.component.html
  app/src/app/modules/main-page/components/profile/profile.component.scss
  app/src/app/modules/main-page/components/profile/profile.component.ts
  app/src/app/modules/main-page/main-page-routing.module.ts
  app/src/app/modules/main-page/main-page.component.html
  app/src/app/modules/main-page/main-page.module.ts
  app/src/index.html
  app/src/styles.scss
Labels: frontend

#30 Feature/be file controller
  api/source/index.ts
  api/source/middleware/uploadMiddleware.ts
  api/source/resources/file/fileController.ts
  api/source/resources/group/groupService.ts
  api/source/resources/user/userController.ts
  api/source/resources/user/userService.ts
  api/source/utils/filePrefix.ts
  api/source/utils/models/baseResponseModel.ts
  api/source/utils/models/controllerModel.ts
  api/source/utils/pathParser.ts
  api/storage/avatar/default.png
Labels: backend
